# =====================================================================
# pcolpicker - PricolorPicker
# 
# ---
# Developed by:
# 	T.Onodera <onodera.takahiro@adways.net>
# Version:
# 	2.0.0
# Cf.:
# 	http://aidiary.hatenablog.com/entry/20091003/1254574041
# 
# 	(C)ADWAYS Inc. all rights reserved.
# 
# =====================================================================

=encoding UTF-8


=head1 NAME

    pcolpicker - get primary color from image file.

=head1 SYNOPSIS


    USAGE:
    ./pcolpicker [-p] [-d|-x] [-b SIZE] [-c SIZE] [-a DEGREE] [-z DEGREE] [-c LEVEL] [IMAGEFILE]
        -p          ... Most used color output picking without range limits
        -m          ... HSV output
        -d          ... Output with decimals
        -x          ... Output with stylesheet format
        -b SIZE     ... 0~5. Bit shift amount of Hue (Default 2)
        -s SIZE     ... 0~7. Bit shift amount of Saturation (Default 4)
        -a DEGREE   ... -179~180. Start degree of exception lange of hue (Default -3)
        -z DEGREE   ... -179~180. End digree of exception lange of hue  (Default 24)
        -c LEVEL    ... 0~255. upper level of chrome to ignore (Default 200)
        -l CLIP     ... 0~0.9. Ratio of cliping (Default 0.1)
        -n:         ... 1,3,5,7 or 9. Normalization level. Omiting or 0 ignores. (Default 0)
        -w:         ... 0.0~2.0. Multipul number to white. (Default 0.0)
        -v          ... Print version
        IMAGEFILE   ... Image file. Omitting means from STDIN

=head1 DESCRIPTION

This program picks up primary color of image file, particularly 
for nailart color on photo of fingers and nails.

The pcolpicker will proceed with several steps.
First, this will clop edges of memoried image data for the aim of
focusing to nails more (almostly nails are centered in picutres)
and redice data to calculate.

And then, the program convert image data from RGB set to HSV one
with reducing color depth.

And calculating and counting high chromatic colors pixcels with
excepting skin color.
(Skin color, about -5~15 degree of hue round and middle-to-low
chromatic will be excepted)

This program will output 6-digits hex number in default.
You can change this to decimal RGB numbers or stylesheet format
like C<#aabbcc> format with options. And also can get HSV data.

=head1 INSTALL

=head2 Requirement

Linux and C<gcc> are needed.
And it need OpenCV2. If you use CentOS, see OpenCV section below for
installing. (Note that to install OpenCV, it is maybe also necessary
to install cmake)

=head2 System Environment

Program requires a library search path, C</usr/local/lib>.
So you should configure system environment or your current one for this
to find it.

The way to config system ones is to make a file which was written
'/usr/local/lib' under the directory, </etc/ld.so.conf.d/>, and execute
C<ldconfig>.

Personal one, set C<LD_LIBRARY_PATH> environment variable before 
executing program. Or, with linux, make ld.so.conf file into C</etc/ld.so.conf.d/>.

=head2 How to make

Change program directory which has sorce, and execute C<make>.

    cd pcolpicker
    make

Executable program, C<pcolpicker>, will be made and copy or move it to
your favorite place.

=head2 Sample

See sample with this page in internal server of Adways.

    http://10.255.32.47/pricol/


=head1 BUG and REQUEST, etc.

Tell or ask me, Onodera. 

Program is written by c++, but almost part is C style coding...
It will be pleasure for me that you will improve, correct bug and custormize this!

=head1 VERSION and HISTORY

Ver. 1.0.0 2014/12/11 First Release

Ver. 2.0.0 2015/06/16 Modified program for using Mat format of OpenCV.

=head1 AUTHOR

T.Onodera, C<< <onodera.takahiro at adways.net> >>

=head1 LICENSE AND COPYRIGHT

(C)ADWAYS Inc. All Rights Reserved.


=cut
